ARG FROM_FILE="autoware"
FROM $FROM_FILE
MAINTAINER Yuma Nihei <yuma.nihei@tier4.jp>

ENV DEBIAN_FRONTEND noninteractive

RUN sudo apt-get install -y -q ros-indigo-sicktoolbox ros-indigo-sicktoolbox-wrapper ros-indigo-novatel-span-driver \
1>/dev/null
